export const HAIKUS: string[] = [
  "the temple bell fades\nbut the fragrance of flowers\ncontinues to ring",
  "an old silent pond\na frog jumps into the pond\nsplash, silence again",
  "in the twilight rain\nthese brilliant-hued hibiscus\na lovely sunset",
  "the light of a candle\nis transferred to another\nspring twilight",
  "over the wintry\nforest, winds howl in rage\nwith no leaves to blow",
  "first autumn morning\nthe mirror I stare into\nshows my father's face",
  "a world of dew\nand within every dewdrop\na world of struggle",
  "the old pond is still\nwaiting for the frog to jump\ninto the silence",
  "sitting quietly\ndoing nothing, spring arrives\ngrass grows by itself",
  "hearing the cuckoo\nI long for the old country\nbeyond the clouds",
  "moonlight on water\nthe heron stands in stillness\nwaiting without thought",
  "morning bell echoes\nthrough the mountain mist it drifts\nsilence returns whole",
  "bamboo shadows sweep\nthe stairs without stirring dust\nmind sweeps the mind clean",
  "one breath at a time\nthe mountain does not hurry\nyet spring still arrives",
  "snow falling gently\non the meditation hall\nthe world disappears",
  "before enlightenment\nchop wood and carry water\nafter, the same",
  "the still mountain lake\nreflects what is already\nhere without effort",
  "a bell rings at dawn\nbirds carry the sound away\nsilence grows deeper",
  "beneath the vast sky\none small candle flame flickers\nholding its own light",
  "watching the incense\nsmoke rise without direction\nthe mind follows too",
  "ten thousand flowers\nin spring, the moon in autumn\na cool summer breeze",
  "no yesterday now\nno tomorrow to arrive\njust this one heartbeat",
  "the cup is useful\nonly when it is empty\nso too the mind rests",
  "after the last bell\nthe silence that follows holds\neverything you need",
  "clouds pass overhead\nthe sky remains where it was\nthoughts pass the same way",
  "do not seek the truth\nonly cease to hold opinions\nand it appears",
  "the candle goes out\nsmoke rises in a thin line\nthen nothing at all",
  "rain on the rooftop\neach drop finds its own way down\nno drop is wasted",
  "walk slowly, breathe deep\nthe path beneath your bare feet\nis already home",
  "where the river bends\nwater does not hesitate\nit simply follows",
];
