appId: com.aunum.meditation-timer
---
# Swipe to settings page (right of timer)
- launchApp
- waitForAnimationToEnd
- assertVisible:
    text: "10:00"
- swipe:
    direction: LEFT
    duration: 400
- waitForAnimationToEnd
- assertVisible:
    text: "Session"
- assertVisible: "Rav Vast"
- assertVisible: "Singing Bowl"
- assertVisible: "Gong"
- assertVisible: "Bell Count"
- assertVisible: "Prep Time"
- assertVisible: "Extra Dim"
- assertVisible: "Night Mode"
- scrollUntilVisible:
    element: "Intervals"
    direction: DOWN
